version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8043:8043"
    environment:
      - SPIDERFOOT_BASE_URL=http://spiderfoot:5001
      - ENV=prod
    networks:
      - spider-net

networks:
  spider-net:
    external: true
    


